### ISSUE TITLE
建议添加常驻透明播放栏、光标自动隐藏

### ISSUE THREAD

**Issue by yijiaqu** [Steve-xmh/applemusic-like-lyrics#27]
感谢作者。目前插件已经可以算是播放页美化插件，可以添加更多播放页个性化功能。

**Comment by Steve-xmh** [comment]
会考虑做设置，目前如果想透明播放栏的话可以尝试以下自定义 CSS 效果：

```css
/* 播放栏的全屏状态 */
.m-player.z-shadow {
  background: transparent !important; /* 可根据自己喜好更换成其他颜色，但是 !important 不能删除 */
  backdrop-filter: blur(4px); /* 背后的内容模糊 */
  /* 可以根据喜好自由添加样式 */
}
```
